# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# pods "red" was not valid:
# * spec.initContainers: Forbidden: pod updates may not add or remove containers
#
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-06-16T02:59:11Z"
  name: red
  namespace: default
  resourceVersion: "822"
  uid: 17fffd99-93d0-4022-943a-a5bc53450bc7
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: red-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-6jwps
      readOnly: true
  initContainers:
  - image: busybox
    name: busybox-container
    command:
    - sh
    - -c
    - sleep 20
  nodeName: controlplane
  restartPolicy: Always
  schedulerName: default-scheduler
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-6jwps
    secret:
      defaultMode: 420
      secretName: default-token-6jwps
